DROP TABLE IF EXISTS currency;
CREATE TABLE IF NOT EXISTS currency (
    id VARCHAR(10) PRIMARY KEY,
    chinese_name VARCHAR(50) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);